export const indexTypesItems = {
    Chapter: [
        {number: '١', name: 'سُــــوْرَۃُ الفَاتِحَة', pageNumber: 1},
        {number: '٢', name: 'سُــــوْرَۃُ البـقرة', pageNumber: 2},
        {number: '٣', name: 'سُــــوْرَۃُ آل عِمْرَان', pageNumber: 50},
        {number: '٤', name: 'سُــــوْرَۃُ النِّسَاء', pageNumber: 77},
        {number: '٥', name: 'سُــــوْرَۃُ المَائِدَة', pageNumber: 106},
        {number: '٦', name: 'سُــــوْرَۃُ الأنعَام', pageNumber: 128},
        {number: '٧', name: 'سُــــوْرَۃُ الأعْرَاف', pageNumber: 151},
        {number: '٨', name: 'سُــــوْرَۃُ الأنفال', pageNumber: 177},
        {number: '٩', name: 'سُــــوْرَۃُ التَّوْبَة', pageNumber: 187},
        {number: '١٠', name: 'سُــــوْرَۃُ يُونُس', pageNumber: 208},
        {number: '١١', name: 'سُــــوْرَۃُ هُود', pageNumber: 221},
        {number: '١٢', name: 'سُــــوْرَۃُ يُوسف', pageNumber: 235},
        {number: '١٣', name: 'سُــــوْرَۃُ الرَّعد', pageNumber: 249},
        {number: '١٤', name: 'سُــــوْرَۃُ إبراهيم', pageNumber: 255},
        {number: '١٥', name: 'سُــــوْرَۃُ الحِجْر', pageNumber: 262},
        {number: '١٦', name: 'سُــــوْرَۃُ النَّحْل', pageNumber: 267},
        {number: '١٧', name: 'سُــــوْرَۃُ الإسرَاء', pageNumber: 282},
        {number: '١٨', name: 'سُــــوْرَۃُ الكهف', pageNumber: 293},
        {number: '١٩', name: 'سُــــوْرَۃُ مَرْيَم', pageNumber: 305},
        {number: '٢٠', name: 'سُــــوْرَۃُ طَه', pageNumber: 312},
        {number: '٢١', name: 'سُــــوْرَۃُ الأنبياء', pageNumber: 322},
        {number: '٢٢', name: 'سُــــوْرَۃُ الحَج', pageNumber: 332},
        {number: '٢٣', name: 'سُــــوْرَۃُ المؤمنون', pageNumber: 342},
        {number: '٢٤', name: 'سُــــوْرَۃُ النُّور', pageNumber: 350},
        {number: '٢٥', name: 'سُــــوْرَۃُ الفرقان', pageNumber: 359},
        {number: '٢٦', name: 'سُــــوْرَۃُ الشعراء', pageNumber: 367},
        {number: '٢٧', name: 'سُــــوْرَۃُ النمل', pageNumber: 377},
        {number: '٢٨', name: 'سُــــوْرَۃُ القصص', pageNumber: 385},
        {number: '٢٩', name: 'سُــــوْرَۃُ العنكبوت', pageNumber: 396},
        {number: '٣٠', name: 'سُــــوْرَۃُ الروم', pageNumber: 404},
        {number: '٣١', name: 'سُــــوْرَۃُ لقمان', pageNumber: 411},
        {number: '٣٢', name: 'سُــــوْرَۃُ السجدة', pageNumber: 415},
        {number: '٣٣', name: 'سُــــوْرَۃُ الأحزاب', pageNumber: 418},
        {number: '٣٤', name: 'سُــــوْرَۃُ سبأ', pageNumber: 428},
        {number: '٣٥', name: 'سُــــوْرَۃُ فاطر', pageNumber: 434},
        {number: '٣٦', name: 'سُــــوْرَۃُ يس', pageNumber: 440},
        {number: '٣٧', name: 'سُــــوْرَۃُ الصافات', pageNumber: 446},
        {number: '٣٨', name: 'سُــــوْرَۃُ ص', pageNumber: 452},
        {number: '٣٩', name: 'سُــــوْرَۃُ الزمر', pageNumber: 458},
        {number: '٤٠', name: 'سُــــوْرَۃُ غافر', pageNumber: 467},
        {number: '٤١', name: 'سُــــوْرَۃُ فصلت', pageNumber: 477},
        {number: '٤٢', name: 'سُــــوْرَۃُ الشورى', pageNumber: 483},
        {number: '٤٣', name: 'سُــــوْرَۃُ الزخرف', pageNumber: 489},
        {number: '٤٤', name: 'سُــــوْرَۃُ الدخان', pageNumber: 496},
        {number: '٤٥', name: 'سُــــوْرَۃُ الجاثية', pageNumber: 499},
        {number: '٤٦', name: 'سُــــوْرَۃُ الأحقاف', pageNumber: 502},
        {number: '٤٧', name: 'سُــــوْرَۃُ محمد', pageNumber: 507},
        {number: '٤٨', name: 'سُــــوْرَۃُ الفتح', pageNumber: 511},
        {number: '٤٩', name: 'سُــــوْرَۃُ الحجرات', pageNumber: 515},
        {number: '٥٠', name: 'سُــــوْرَۃُ ق', pageNumber: 518},
        {number: '٥١', name: 'سُــــوْرَۃُ الذاريات', pageNumber: 520},
        {number: '٥٢', name: 'سُــــوْرَۃُ الطور', pageNumber: 523},
        {number: '٥٣', name: 'سُــــوْرَۃُ النجم', pageNumber: 526},
        {number: '٥٤', name: 'سُــــوْرَۃُ القمر', pageNumber: 528},
        {number: '٥٥', name: 'سُــــوْرَۃُ الرحمن', pageNumber: 531},
        {number: '٥٦', name: 'سُــــوْرَۃُ الواقعة', pageNumber: 534},
        {number: '٥٧', name: 'سُــــوْرَۃُ الحديد', pageNumber: 537},
        {number: '٥٨', name: 'سُــــوْرَۃُ المجادلة', pageNumber: 542},
        {number: '٥٩', name: 'سُــــوْرَۃُ الحشر', pageNumber: 545},
        {number: '٦٠', name: 'سُــــوْرَۃُ الممتحنة', pageNumber: 548},
        {number: '٦١', name: 'سُــــوْرَۃُ الصف', pageNumber: 551},
        {number: '٦٢', name: 'سُــــوْرَۃُ الجمعة', pageNumber: 553},
        {number: '٦٣', name: 'سُــــوْرَۃُ المنافقون', pageNumber: 554},
        {number: '٦٤', name: 'سُــــوْرَۃُ التغابن', pageNumber: 556},
        {number: '٦٥', name: 'سُــــوْرَۃُ الطلاق', pageNumber: 558},
        {number: '٦٦', name: 'سُــــوْرَۃُ التحريم', pageNumber: 560},
        {number: '٦٧', name: 'سُــــوْرَۃُ الملك', pageNumber: 562},
        {number: '٦٨', name: 'سُــــوْرَۃُ القلم', pageNumber: 564},
        {number: '٦٩', name: 'سُــــوْرَۃُ الحاقة', pageNumber: 566},
        {number: '٧٠', name: 'سُــــوْرَۃُ المعارج', pageNumber: 568},
        {number: '٧١', name: 'سُــــوْرَۃُ نوح', pageNumber: 570},
        {number: '٧٢', name: 'سُــــوْرَۃُ الجن', pageNumber: 572},
        {number: '٧٣', name: 'سُــــوْرَۃُ المزمل', pageNumber: 574},
        {number: '٧٤', name: 'سُــــوْرَۃُ المدثر', pageNumber: 575},
        {number: '٧٥', name: 'سُــــوْرَۃُ القيامة', pageNumber: 577},
        {number: '٧٦', name: 'سُــــوْرَۃُ الإنسان', pageNumber: 578},
        {number: '٧٧', name: 'سُــــوْرَۃُ المرسلات', pageNumber: 580},
        {number: '٧٨', name: 'سُــــوْرَۃُ النبأ', pageNumber: 582},
        {number: '٧٩', name: 'سُــــوْرَۃُ النازعات', pageNumber: 583},
        {number: '٨٠', name: 'سُــــوْرَۃُ عبس', pageNumber: 585},
        {number: '٨١', name: 'سُــــوْرَۃُ التكوير', pageNumber: 586},
        {number: '٨٢', name: 'سُــــوْرَۃُ الإنفطار', pageNumber: 587},
        {number: '٨٣', name: 'سُــــوْرَۃُ المطففين', pageNumber: 587},
        {number: '٨٤', name: 'سُــــوْرَۃُ الإنشقاق', pageNumber: 589},
        {number: '٨٥', name: 'سُــــوْرَۃُ البروج', pageNumber: 590},
        {number: '٨٦', name: 'سُــــوْرَۃُ الطارق', pageNumber: 591},
        {number: '٨٧', name: 'سُــــوْرَۃُ الأعلى', pageNumber: 591},
        {number: '٨٨', name: 'سُــــوْرَۃُ الغاشية', pageNumber: 592},
        {number: '٨٩', name: 'سُــــوْرَۃُ الفجر', pageNumber: 593},
        {number: '٩٠', name: 'سُــــوْرَۃُ البلد', pageNumber: 594},
        {number: '٩١', name: 'سُــــوْرَۃُ الشمس', pageNumber: 595},
        {number: '٩٢', name: 'سُــــوْرَۃُ الليل', pageNumber: 595},
        {number: '٩٣', name: 'سُــــوْرَۃُ الضحى', pageNumber: 596},
        {number: '٩٤', name: 'سُــــوْرَۃُ الشرح', pageNumber: 596},
        {number: '٩٥', name: 'سُــــوْرَۃُ التين', pageNumber: 597},
        {number: '٩٦', name: 'سُــــوْرَۃُ العلق', pageNumber: 597},
        {number: '٩٧', name: 'سُــــوْرَۃُ القدر', pageNumber: 598},
        {number: '٩٨', name: 'سُــــوْرَۃُ البينة', pageNumber: 598},
        {number: '٩٩', name: 'سُــــوْرَۃُ الزلزلة', pageNumber: 599},
        {number: '١٠٠', name: 'سُــــوْرَۃُ العاديات', pageNumber: 599},
        {number: '١٠١', name: 'سُــــوْرَۃُ القارعة', pageNumber: 600},
        {number: '١٠٢', name: 'سُــــوْرَۃُ التكاثر', pageNumber: 600},
        {number: '١٠٣', name: 'سُــــوْرَۃُ العصر', pageNumber: 601},
        {number: '١٠٤', name: 'سُــــوْرَۃُ الهمزة', pageNumber: 601},
        {number: '١٠٥', name: 'سُــــوْرَۃُ الفيل', pageNumber: 601},
        {number: '١٠٦', name: 'سُــــوْرَۃُ قريش', pageNumber: 602},
        {number: '١٠٧', name: 'سُــــوْرَۃُ الماعون', pageNumber: 602},
        {number: '١٠٨', name: 'سُــــوْرَۃُ الكوثر', pageNumber: 602},
        {number: '١٠٩', name: 'سُــــوْرَۃُ الكافرون', pageNumber: 603},
        {number: '١١٠', name: 'سُــــوْرَۃُ النصر', pageNumber: 603},
        {number: '١١١', name: 'سُــــوْرَۃُ المسد', pageNumber: 603},
        {number: '١١٢', name: 'سُــــوْرَۃُ الإخلاص', pageNumber: 604},
        {number: '١١٣', name: 'سُــــوْرَۃُ الفلق', pageNumber: 604},
        {number: '١١٤', name: 'سُــــوْرَۃُ الناس', pageNumber: 604}
        ],
    Juz: [
        {number: '١', name: 'الجزء الأول', pageNumber: 1},
        {number: '٢', name: 'الجزء الثاني', pageNumber: 22},
        {number: '٣', name: 'الجزء الثالث', pageNumber: 42},
        {number: '٤', name: 'الجزء الرابع', pageNumber: 62},
        {number: '٥', name: 'الجزء الخامس', pageNumber: 82},
        {number: '٦', name: 'الجزء السادس', pageNumber: 102},
        {number: '٧', name: 'الجزء السابع', pageNumber: 121},
        {number: '٨', name: 'الجزء الثامن', pageNumber: 142},
        {number: '٩', name: 'الجزء التاسع', pageNumber: 162},
        {number: '١٠', name: 'الجزء العاشر', pageNumber: 182},
        {number: '١١', name: 'الجزء الحادي عشر', pageNumber: 201},
        {number: '١٢', name: 'الجزء الثاني عشر', pageNumber: 222},
        {number: '١٣', name: 'الجزء الثالث عشر', pageNumber: 242},
        {number: '١٤', name: 'الجزء الرابع عشر', pageNumber: 262},
        {number: '١٥', name: 'الجزء الخامس عشر', pageNumber: 282},
        {number: '١٦', name: 'الجزء السادس عشر', pageNumber: 302},
        {number: '١٧', name: 'الجزء السابع عشر', pageNumber: 322},
        {number: '١٨', name: 'الجزء الثامن عشر', pageNumber: 342},
        {number: '١٩', name: 'الجزء التاسع عشر', pageNumber: 362},
        {number: '٢٠', name: 'الجزء العشرون', pageNumber: 382},
        {number: '٢١', name: 'الجزء الحادي والعشرون', pageNumber: 402},
        {number: '٢٢', name: 'الجزء الثاني والعشرون', pageNumber: 422},
        {number: '٢٣', name: 'الجزء الثالث والعشرون', pageNumber: 442},
        {number: '٢٤', name: 'الجزء الرابع والعشرون', pageNumber: 462},
        {number: '٢٥', name: 'الجزء الخامس والعشرون', pageNumber: 482},
        {number: '٢٦', name: 'الجزء السادس والعشرون', pageNumber: 502},
        {number: '٢٧', name: 'الجزء السابع والعشرون', pageNumber: 522},
        {number: '٢٨', name: 'الجزء الثامن والعشرون', pageNumber: 542},
        {number: '٢٩', name: 'الجزء التاسع والعشرون', pageNumber: 562},
        {number: '٣٠', name: 'الجزء الثلاثون', pageNumber: 582}
      ]
      
  };