export const indexTypesItems = {
    Chapter: [
        {number: '١', name: 'سُــــوْرَةُ الفَاتِحَة', pageNumber: 1},
        {number: '٢', name: 'سُــــوْرَةُ البـقرة', pageNumber: 2},
        {number: '٣', name: 'سُــــوْرَةُ آل عِمْرَان', pageNumber: 50},
        {number: '٤', name: 'سُــــوْرَةُ النِّسَاء', pageNumber: 77},
        {number: '٥', name: 'سُــــوْرَةُ المَائِدَة', pageNumber: 106},
        {number: '٦', name: 'سُــــوْرَةُ الأنعَام', pageNumber: 128},
        {number: '٧', name: 'سُــــوْرَةُ الأعْرَاف', pageNumber: 151},
        {number: '٨', name: 'سُــــوْرَةُ الأنفال', pageNumber: 177},
        {number: '٩', name: 'سُــــوْرَةُ التَّوْبَة', pageNumber: 187},
        {number: '١٠', name: 'سُــــوْرَةُ يُونُس', pageNumber: 208},
        {number: '١١', name: 'سُــــوْرَةُ هُود', pageNumber: 221},
        {number: '١٢', name: 'سُــــوْرَةُ يُوسف', pageNumber: 235},
        {number: '١٣', name: 'سُــــوْرَةُ الرَّعد', pageNumber: 249},
        {number: '١٤', name: 'سُــــوْرَةُ إبراهيم', pageNumber: 255},
        {number: '١٥', name: 'سُــــوْرَةُ الحِجْر', pageNumber: 262},
        {number: '١٦', name: 'سُــــوْرَةُ النَّحْل', pageNumber: 267},
        {number: '١٧', name: 'سُــــوْرَةُ الإسرَاء', pageNumber: 282},
        {number: '١٨', name: 'سُــــوْرَةُ الكهف', pageNumber: 293},
        {number: '١٩', name: 'سُــــوْرَةُ مَرْيَم', pageNumber: 305},
        {number: '٢٠', name: 'سُــــوْرَةُ طَه', pageNumber: 312},
        {number: '٢١', name: 'سُــــوْرَةُ الأنبياء', pageNumber: 322},
        {number: '٢٢', name: 'سُــــوْرَةُ الحَج', pageNumber: 332},
        {number: '٢٣', name: 'سُــــوْرَةُ المؤمنون', pageNumber: 342},
        {number: '٢٤', name: 'سُــــوْرَةُ النُّور', pageNumber: 350},
        {number: '٢٥', name: 'سُــــوْرَةُ الفرقان', pageNumber: 359},
        {number: '٢٦', name: 'سُــــوْرَةُ الشعراء', pageNumber: 367},
        {number: '٢٧', name: 'سُــــوْرَةُ النمل', pageNumber: 377},
        {number: '٢٨', name: 'سُــــوْرَةُ القصص', pageNumber: 385},
        {number: '٢٩', name: 'سُــــوْرَةُ العنكبوت', pageNumber: 396},
        {number: '٣٠', name: 'سُــــوْرَةُ الروم', pageNumber: 404},
        {number: '٣١', name: 'سُــــوْرَةُ لقمان', pageNumber: 411},
        {number: '٣٢', name: 'سُــــوْرَةُ السجدة', pageNumber: 415},
        {number: '٣٣', name: 'سُــــوْرَةُ الأحزاب', pageNumber: 418},
        {number: '٣٤', name: 'سُــــوْرَةُ سبأ', pageNumber: 428},
        {number: '٣٥', name: 'سُــــوْرَةُ فاطر', pageNumber: 434},
        {number: '٣٦', name: 'سُــــوْرَةُ يس', pageNumber: 440},
        {number: '٣٧', name: 'سُــــوْرَةُ الصافات', pageNumber: 446},
        {number: '٣٨', name: 'سُــــوْرَةُ ص', pageNumber: 452},
        {number: '٣٩', name: 'سُــــوْرَةُ الزمر', pageNumber: 458},
        {number: '٤٠', name: 'سُــــوْرَةُ غافر', pageNumber: 467},
        {number: '٤١', name: 'سُــــوْرَةُ فصلت', pageNumber: 477},
        {number: '٤٢', name: 'سُــــوْرَةُ الشورى', pageNumber: 483},
        {number: '٤٣', name: 'سُــــوْرَةُ الزخرف', pageNumber: 489},
        {number: '٤٤', name: 'سُــــوْرَةُ الدخان', pageNumber: 496},
        {number: '٤٥', name: 'سُــــوْرَةُ الجاثية', pageNumber: 499},
        {number: '٤٦', name: 'سُــــوْرَةُ الأحقاف', pageNumber: 502},
        {number: '٤٧', name: 'سُــــوْرَةُ محمد', pageNumber: 507},
        {number: '٤٨', name: 'سُــــوْرَةُ الفتح', pageNumber: 511},
        {number: '٤٩', name: 'سُــــوْرَةُ الحجرات', pageNumber: 515},
        {number: '٥٠', name: 'سُــــوْرَةُ ق', pageNumber: 518},
        {number: '٥١', name: 'سُــــوْرَةُ الذاريات', pageNumber: 520},
        {number: '٥٢', name: 'سُــــوْرَةُ الطور', pageNumber: 523},
        {number: '٥٣', name: 'سُــــوْرَةُ النجم', pageNumber: 526},
        {number: '٥٤', name: 'سُــــوْرَةُ القمر', pageNumber: 528},
        {number: '٥٥', name: 'سُــــوْرَةُ الرحمن', pageNumber: 531},
        {number: '٥٦', name: 'سُــــوْرَةُ الواقعة', pageNumber: 534},
        {number: '٥٧', name: 'سُــــوْرَةُ الحديد', pageNumber: 537},
        {number: '٥٨', name: 'سُــــوْرَةُ المجادلة', pageNumber: 542},
        {number: '٥٩', name: 'سُــــوْرَةُ الحشر', pageNumber: 545},
        {number: '٦٠', name: 'سُــــوْرَةُ الممتحنة', pageNumber: 548},
        {number: '٦١', name: 'سُــــوْرَةُ الصف', pageNumber: 551},
        {number: '٦٢', name: 'سُــــوْرَةُ الجمعة', pageNumber: 553},
        {number: '٦٣', name: 'سُــــوْرَةُ المنافقون', pageNumber: 554},
        {number: '٦٤', name: 'سُــــوْرَةُ التغابن', pageNumber: 556},
        {number: '٦٥', name: 'سُــــوْرَةُ الطلاق', pageNumber: 558},
        {number: '٦٦', name: 'سُــــوْرَةُ التحريم', pageNumber: 560},
        {number: '٦٧', name: 'سُــــوْرَةُ الملك', pageNumber: 562},
        {number: '٦٨', name: 'سُــــوْرَةُ القلم', pageNumber: 564},
        {number: '٦٩', name: 'سُــــوْرَةُ الحاقة', pageNumber: 566},
        {number: '٧٠', name: 'سُــــوْرَةُ المعارج', pageNumber: 568},
        {number: '٧١', name: 'سُــــوْرَةُ نوح', pageNumber: 570},
        {number: '٧٢', name: 'سُــــوْرَةُ الجن', pageNumber: 572},
        {number: '٧٣', name: 'سُــــوْرَةُ المزمل', pageNumber: 574},
        {number: '٧٤', name: 'سُــــوْرَةُ المدثر', pageNumber: 575},
        {number: '٧٥', name: 'سُــــوْرَةُ القيامة', pageNumber: 577},
        {number: '٧٦', name: 'سُــــوْرَةُ الإنسان', pageNumber: 578},
        {number: '٧٧', name: 'سُــــوْرَةُ المرسلات', pageNumber: 580},
        {number: '٧٨', name: 'سُــــوْرَةُ النبأ', pageNumber: 582},
        {number: '٧٩', name: 'سُــــوْرَةُ النازعات', pageNumber: 583},
        {number: '٨٠', name: 'سُــــوْرَةُ عبس', pageNumber: 585},
        {number: '٨١', name: 'سُــــوْرَةُ التكوير', pageNumber: 586},
        {number: '٨٢', name: 'سُــــوْرَةُ الإنفطار', pageNumber: 587},
        {number: '٨٣', name: 'سُــــوْرَةُ المطففين', pageNumber: 587},
        {number: '٨٤', name: 'سُــــوْرَةُ الإنشقاق', pageNumber: 589},
        {number: '٨٥', name: 'سُــــوْرَةُ البروج', pageNumber: 590},
        {number: '٨٦', name: 'سُــــوْرَةُ الطارق', pageNumber: 591},
        {number: '٨٧', name: 'سُــــوْرَةُ الأعلى', pageNumber: 591},
        {number: '٨٨', name: 'سُــــوْرَةُ الغاشية', pageNumber: 592},
        {number: '٨٩', name: 'سُــــوْرَةُ الفجر', pageNumber: 593},
        {number: '٩٠', name: 'سُــــوْرَةُ البلد', pageNumber: 594},
        {number: '٩١', name: 'سُــــوْرَةُ الشمس', pageNumber: 595},
        {number: '٩٢', name: 'سُــــوْرَةُ الليل', pageNumber: 595},
        {number: '٩٣', name: 'سُــــوْرَةُ الضحى', pageNumber: 596},
        {number: '٩٤', name: 'سُــــوْرَةُ الشرح', pageNumber: 596},
        {number: '٩٥', name: 'سُــــوْرَةُ التين', pageNumber: 597},
        {number: '٩٦', name: 'سُــــوْرَةُ العلق', pageNumber: 597},
        {number: '٩٧', name: 'سُــــوْرَةُ القدر', pageNumber: 598},
        {number: '٩٨', name: 'سُــــوْرَةُ البينة', pageNumber: 598},
        {number: '٩٩', name: 'سُــــوْرَةُ الزلزلة', pageNumber: 599},
        {number: '١٠٠', name: 'سُــــوْرَةُ العاديات', pageNumber: 599},
        {number: '١٠١', name: 'سُــــوْرَةُ القارعة', pageNumber: 600},
        {number: '١٠٢', name: 'سُــــوْرَةُ التكاثر', pageNumber: 600},
        {number: '١٠٣', name: 'سُــــوْرَةُ العصر', pageNumber: 601},
        {number: '١٠٤', name: 'سُــــوْرَةُ الهمزة', pageNumber: 601},
        {number: '١٠٥', name: 'سُــــوْرَةُ الفيل', pageNumber: 601},
        {number: '١٠٦', name: 'سُــــوْرَةُ قريش', pageNumber: 602},
        {number: '١٠٧', name: 'سُــــوْرَةُ الماعون', pageNumber: 602},
        {number: '١٠٨', name: 'سُــــوْرَةُ الكوثر', pageNumber: 602},
        {number: '١٠٩', name: 'سُــــوْرَةُ الكافرون', pageNumber: 603},
        {number: '١١٠', name: 'سُــــوْرَةُ النصر', pageNumber: 603},
        {number: '١١١', name: 'سُــــوْرَةُ المسد', pageNumber: 603},
        {number: '١١٢', name: 'سُــــوْرَةُ الإخلاص', pageNumber: 604},
        {number: '١١٣', name: 'سُــــوْرَةُ الفلق', pageNumber: 604},
        {number: '١١٤', name: 'سُــــوْرَةُ الناس', pageNumber: 604}
        ],
    Juz: [
        {number: '١', name: 'الجزء الأول', pageNumber: 1},
        {number: '٢', name: 'الجزء الثاني', pageNumber: 22},
        {number: '٣', name: 'الجزء الثالث', pageNumber: 42},
        {number: '٤', name: 'الجزء الرابع', pageNumber: 62},
        {number: '٥', name: 'الجزء الخامس', pageNumber: 82},
        {number: '٦', name: 'الجزء السادس', pageNumber: 102},
        {number: '٧', name: 'الجزء السابع', pageNumber: 121},
        {number: '٨', name: 'الجزء الثامن', pageNumber: 142},
        {number: '٩', name: 'الجزء التاسع', pageNumber: 162},
        {number: '١٠', name: 'الجزء العاشر', pageNumber: 182},
        {number: '١١', name: 'الجزء الحادي عشر', pageNumber: 201},
        {number: '١٢', name: 'الجزء الثاني عشر', pageNumber: 222},
        {number: '١٣', name: 'الجزء الثالث عشر', pageNumber: 242},
        {number: '١٤', name: 'الجزء الرابع عشر', pageNumber: 262},
        {number: '١٥', name: 'الجزء الخامس عشر', pageNumber: 282},
        {number: '١٦', name: 'الجزء السادس عشر', pageNumber: 302},
        {number: '١٧', name: 'الجزء السابع عشر', pageNumber: 322},
        {number: '١٨', name: 'الجزء الثامن عشر', pageNumber: 342},
        {number: '١٩', name: 'الجزء التاسع عشر', pageNumber: 362},
        {number: '٢٠', name: 'الجزء العشرون', pageNumber: 382},
        {number: '٢١', name: 'الجزء الحادي والعشرون', pageNumber: 402},
        {number: '٢٢', name: 'الجزء الثاني والعشرون', pageNumber: 422},
        {number: '٢٣', name: 'الجزء الثالث والعشرون', pageNumber: 442},
        {number: '٢٤', name: 'الجزء الرابع والعشرون', pageNumber: 462},
        {number: '٢٥', name: 'الجزء الخامس والعشرون', pageNumber: 482},
        {number: '٢٦', name: 'الجزء السادس والعشرون', pageNumber: 502},
        {number: '٢٧', name: 'الجزء السابع والعشرون', pageNumber: 522},
        {number: '٢٨', name: 'الجزء الثامن والعشرون', pageNumber: 542},
        {number: '٢٩', name: 'الجزء التاسع والعشرون', pageNumber: 562},
        {number: '٣٠', name: 'الجزء الثلاثون', pageNumber: 582}
      ]
      
  };